### ISSUE TITLE
await next如果不执行下一个路由

### ISSUE THREAD

**Issue by czl0325** [TencentCloudBase/tcb-router#4]
```
app.router('join', async(ctx, next)=>{
    if (event.activity_id == null) {
      result.code = 100
      result.message = "缺少参数activity_id"
     ctx.body = result
     await next()
    } 
    ......省略代码
    ctx.body = result
  })
```

如果出现错误，想要直接返回ctx.body给用户，不再执行下一个中间件了，怎么写？

**Comment by flytam** [comment]
在tcb-router的设计中，中间件是在router之前执行的
[代码](https://github.com/TencentCloudBase/tcb-router/blob/master/src/index.js#L98)

你的样例代码后面的use中间件其实在router前面就执行了。如果要use或者router 出现错误不执行后面的话，不执行next方法就可以了

**Comment by czl0325** [comment]
> 在tcb-router的设计中，中间件是在router之前执行的
> [代码](https://github.com/TencentCloudBase/tcb-router/blob/master/src/index.js#L98)
> 
> 你的样例代码后面的use中间件其实在router前面就执行了。如果要use或者router 出现错误不执行后面的话，不执行next方法就可以了

```
app.router('router1', async(ctx, next)=>{
    if (发生错误) {
      返回信息给用户
      ctx.body = result
      await next()
    } 
    ......如果正确的执行代码代码
    ctx.body = result
  })
app.router('router2', async(ctx, next)=>{
    ctx.body = result
  })
```

假设router1发生错误，就马上返回给用户，下面的正确代码和router2都不执行，在if里面加await next()这样写对吗？如果把await next()换成return不行

**Comment by flytam** [comment]
router1和router2 怎么会存在同时执行的情况呢？两个不同的路由

如果是下面这个的话。
```js
app.router('router1', async(ctx, next)=>{
    if (发生错误) {
      返回信息给用户
      ctx.body = result
      return
    } 
    ......如果正确的执行代码代码
    ctx.body = result
    await next()
  })
app.router('router1', async(ctx, next)=>{
// 正确的话会继续到这里
    ctx.body = result
  })
```
发生错误，不会进入到后面的router1路由。next就是指向的下一个执行的中间件/路由 函数。这里的中间件调用逻辑和koa实现是基本一致的

**Comment by czl0325** [comment]
> ```js
> app.router('router1', async(ctx, next)=>{
>     if (发生错误) {
>       返回信息给用户
>       ctx.body = result
>       return
>     } 
>     ......如果正确的执行代码代码
>     ctx.body = result
>     await next()
>   })
> app.router('router1', async(ctx, next)=>{
> // 正确的话会继续到这里
>     ctx.body = result
>   })
> ```

```
exports.main = async(event, context) => {
app.router('router1', async(ctx, next)=>{
    if (发生错误) {
      返回信息给用户
      result = {code:100,msg:"数据错误"}
      ctx.body = result
      return     //return没有效果，下面代码还是会执行
    } 
    ......如果正确的执行代码代码
    ctx.body = result
  })
app.router('router2', async(ctx, next)=>{
// 正确的话会继续到这里
    ctx.body = result
  })
```
这么写的话，在发生错误的时候，return不起效果，还是会执行下面正确的执行代码，如何不执行下面

**Comment by flytam** [comment]
![image](https://user-images.githubusercontent.com/20512530/69950493-5a8b9f00-152e-11ea-8a50-c480670ebba4.png)
@czl0325 czl0325
没问题呀。如果可以的话 提供下最小复现样例代码？
