### ISSUE TITLE
希望能兼容腾讯云的云函数。

### ISSUE THREAD

**Issue by myliweihao** [TencentCloudBase/tcb-router#5]
希望这个功能能兼容腾讯云云函数，谢谢。
“https://console.cloud.tencent.com/scf/index?rid=1”

**Comment by flytam** [comment]
@myliweihao 云函数也能用的呀。用法一样的。实例化TcbRouter的时候传进event就好了（参考readme）。调用云函数的时候传递`{$url:'你的路由'}`就可以了

**Comment by myliweihao** [comment]
你好，腾讯云云函数可以使用了。
请问如何要像koa生成器那种，把功能单独做成一个个js模块，谢谢。

`
//app.js
const users = require('./routes/users')
app.use(users.routes(), users.allowedMethods())

//routes/users.js
const router = require('koa-router')()
router.prefix('/users')
router.get('/', function (ctx, next) {
  ctx.body = 'this is a users response!'
})
router.get('/bar', function (ctx, next) {
  ctx.body = 'this is a users/bar response'
})
module.exports = router
`

**Comment by flytam** [comment]
没看懂你说的意思。自己抽离模块就好了吧。
